### ISSUE TITLE
Documentar roadmap de papéis

### ISSUE THREAD

**Issue by WelisonR** [fga-eps-mds/EPS-2020-2-G3#30]
## Descrição

Issue destinada a documentar o roadmap de papéis e atividades que serão desenvolvidas durante a elaboração do projeto.

## Tarefas

- [x] Documentar roadmap do scrum master;
- [x] Documentar roadmap do devops;
- [x] Documentar roadmap do product owner / product manager;
- [x] Documentar roadmap do arquiteto;
- [x] Documentar roadmap do analista de dados.

## Critérios de Aceitação

- [x] Documentação de todos os papéis;
- [x] Documentar na wiki.

## Observação

* Seguir estrutura de um EAP ou similar (dividir por papéis).
